# Site-wide variables.
title: Formn Docs

# Build settings
markdown: kramdown
theme: just-the-docs
exclude:
  - docker-compose.yml
  - docker-compose.build.yml
  - Gemfile
  - Gemfile.lock

baseurl: "/doc/formn/5.x.x"

# Just the Docs config.
search_enabled: true

aux_links:
  "Formn on GitHub":
    - "//github.com/benbotto/formn/tree/master"
  "API Docs":
    - "/doc/formn/5.x.x/api-doc/latest/globals.html"
